### ISSUE TITLE
Rebuild image nightly

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-build-container#342]
#### User Story

As a user, I want to make sure to have the latest security patches in the build container.

#### Background (Optional)

We currently restage the application nightly, but do not rebuild it, let's rebuild it too!

#### Acceptance Criteria

- [x] Concourse rebuilds and pushes the new image nightly
- [x] Change made live via deploy federalist-garden-build and set Concourse pipeline.

#### Implementation outline (if higher than "low" effort):

- [x] Concourse CircleCI pipeline to rebuild/push image during the nightly job
- [x] Set new Concourse pipeline

**Comment by apburnes** [comment]
Completed. Unpaused pipeline
