### ISSUE TITLE
Cache build dependencies

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-build-container#377]
Installing dependencies can take >2 minutes of build time and aren't necessarily changing very often (especially on content edits). It would reduce overall build times if we cached `gems` and `node_modules`

## Notes

- I've sketched out an initial attempt at https://github.com/cloud-gov/pages-build-container/pull/378

## Acceptance Criteria

- [x] Determine ideal approach/structure
- [x] Optional: add build tests
- [x] Confirm functionality in staging
- [x] Document the feature and addition to federalist.json

## Security/Performance notes about cache implementations
- Option 1. We store cache files in the bucket we serve the site from. They might be exposed to the internet but are generally not private. We could workaround this by adding to the bucket root (not the `_site` folder)
- Option 2. We store cache files in a single bucket. There might be crossover between multiple sites' caches which is good from a performance perspective but potentially insecure
- Option 3. We store cache files in a new bucket, per site. Most secure option in terms of file exposure but presents a larger (numerically) attack surface. Also runs us more quickly into our AWS account limit

**Comment by drewbo** [comment]
Update: Option 1 is still the preferred method but a slight complication: the bucket itself is open to all requests (not just via the proxy). Updated strategy to keep the cache files not publicly accessible:
- The proxy itself already only matches [certain paths](https://github.com/cloud-gov/pages-proxy/blob/staging/nginx.conf#L95) so as long as traffic has to go through the proxy to get to the bucket, no requests will reach the `_cache` folder in the bucket.
- The bucket policy can be changed to only allow requests from a certain IP range or VPC endpoint (set in the federalist [s3 broker config](https://github.com/cloud-gov/cg-deploy-s3-broker/blob/master/federalist-config-template.yml)) to restrict incoming traffic to only that originating from the proxy. This will need to be updated for new buckets and a batch job for existing buckets.

**Comment by drewbo** [comment]
Bucket polices are updated via https://github.com/cloud-gov/pages-core/pull/4027 and https://github.com/cloud-gov/cg-deploy-s3-broker/pull/47

**Comment by apburnes** [comment]
Closed by #394 #392 and https://github.com/cloud-gov/cg-site/pull/2237
