### ISSUE TITLE
Review the Ruby 2.7 EOL

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-build-container#412]
With the Ruby 2.7 EOL in the near future, we will need to update and notify users. 

## Acceptance Criteria
- [ ] Notify users of the upcoming EOL
- [ ] Research and document a migration path for sites using jekyll and ruby <=2.7 to use ruby 3.1
- [ ] Deprecate [our jekyll template](https://github.com/cloud-gov/pages-uswds-jekyll)
- [ ] Update default ruby version to 3.1

**Comment by drewbo** [comment]
@apburnes I'd like to rework this issue to use its original topic (what to do with Ruby 2.7 EOL) and break out the build container topic.

Re: ruby, it would be good to fairly soon bump our default version to 3.1 ([supported for two more years but not the most recent](https://endoflife.date/ruby)) but we'll need to provide a bunch of folks with a migration pathway, especially those that I previously recommended to drop their `.ruby-version` file to use the default and get faster installs.

**Comment by apburnes** [comment]
Sent notice via govconnect to cloud.gov Pages users.
