### ISSUE TITLE
Add dependency auditing/monitoring

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-build-container#458]
We'd like to ensure that we don't merge vulnerable dependencies into this repo.

## Notes

- https://github.com/cloud-gov/pages-core/issues/4217
- https://github.com/pypa/pip-audit
- https://github.com/cloud-gov/pages-build-container/pull/460
- https://github.com/cloud-gov/internal-docs/blob/main/docs/runbooks/Pages/dependabot-security.md
- https://github.com/cloud-gov/pages-build-container/pull/464

## Acceptance Criteria

- [x] Add dependency auditing to the CI pipeline
- [x] Enable dependabot security scanning via Github Security configuration
- [x] Update internal docs/runbook to indicate that our quarterly process should apply to this repo as well

**Comment by svenaas** [comment]
Dependency auditing added with #460

**Comment by svenaas** [comment]
@drewbo It [looks like](https://github.com/cloud-gov/pages-build-container/settings/security_analysis) Dependabot security scanning is already enabled. Or did you intend a change in our [rules](https://github.com/cloud-gov/pages-build-container/settings/dependabot_rules)?

**Comment by drewbo** [comment]
Ideally I'd like to configure it like https://github.com/cloud-gov/pages-core/pull/4222/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28. The intent is to not open PRs for version updates (seemingly working) and to preface other PRs with `[ci skip]` (not working)

**Comment by drewbo** [comment]
Also let's update the runbook/internal doc to indicate that our quarterly process should apply to this repo as well.

**Comment by svenaas** [comment]
> Ideally I'd like to configure it like https://github.com/cloud-gov/pages-core/pull/4222/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28. The intent is to not open PRs for version updates (seemingly working) and to preface other PRs with `[ci skip]` (not working)

Should it have a schedule (`interval: weekly`) like current pages-core?
